//! Substitute outlines for fonts a PDF does not embed — in every script.
//!
//! A PDF may name any of the 14 standard fonts, or any installed font, and
//! embed nothing; or embed a program this renderer cannot read. Drawing
//! nothing turned such documents into blank pages, and drawing only Roboto
//! left every non-Latin character blank. The document's own `/Widths` still
//! place each glyph, so a substitute only has to supply shapes.
//!
//! A character is looked for, in order, in:
//!
//! 1. a Latin face matched to the original's style — the device's own serif
//!    or monospace face for Times or Courier, Roboto otherwise;
//! 2. the bundled Noto faces (`data/fallback-fonts.bin`), which cover the
//!    scripts of living languages, mathematics and symbols on every device;
//! 3. the device's installed fonts (see [`super::system`]), which is where
//!    Chinese, Japanese and Korean come from: every phone and desktop ships
//!    a CJK face, and bundling one would add twenty megabytes. Han
//!    characters prefer a face for the document's own region, since the
//!    same code point is drawn differently in Japan, China and Korea.
//!
//! Outlines are returned in 1000 units per em whatever the face's own em,
//! because one substituted font may borrow glyphs from several faces.

use std::collections::HashMap;
use std::path::PathBuf;
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::{Arc, Mutex, OnceLock};

use super::system::{self, FaceInfo};
use super::truetype::TrueTypeFont;
use crate::geom::{Matrix, Path};

const ROBOTO_REGULAR: &[u8] = include_bytes!("../../fonts/Roboto-Regular.ttf");
const ROBOTO_BOLD: &[u8] = include_bytes!("../../fonts/Roboto-Bold.ttf");

/// The bundled Noto faces, generated by the `build_fallback_bundle` example.
static BUNDLE: &[u8] = include_bytes!("../../data/fallback-fonts.bin");
const MAGIC: &[u8; 8] = b"PDFFONT1";

/// How much to lean a synthesised italic, as a shear on x per unit y.
/// 0.21 is about 12 degrees, the slope most oblique faces use.
const OBLIQUE_SHEAR: f64 = 0.21;

/// Outlines and advances come back in this many units per em.
const UNITS: f64 = 1000.0;

static SYSTEM_FONTS: AtomicBool = AtomicBool::new(true);
static EXTRA_DIRECTORIES: Mutex<Vec<PathBuf>> = Mutex::new(Vec::new());

/// Whether installed fonts may be used. Off makes rendering depend only on
/// what ships in the library — reproducible across machines, for tests.
pub fn set_system_fonts_enabled(enabled: bool) {
    SYSTEM_FONTS.store(enabled, Ordering::Relaxed);
}

/// Another directory to look for installed fonts in, such as fonts an app
/// ships or downloads itself. Takes effect if added before the first lookup
/// that needs installed fonts.
pub fn add_font_directory(path: impl Into<PathBuf>) {
    if let Ok(mut dirs) = EXTRA_DIRECTORIES.lock() {
        dirs.push(path.into());
    }
}

/// Which substitute face a font dictionary should borrow.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct FallbackStyle {
    pub bold: bool,
    pub italic: bool,
    /// Courier and friends: every glyph advances 600/1000 em.
    pub fixed_pitch: bool,
    /// Times, Mincho, Song: a design with serifs.
    pub serif: bool,
}

impl FallbackStyle {
    /// Read weight and slope out of a `/BaseFont` name and the descriptor
    /// flags. Names look like `AAAAAA+Helvetica-BoldOblique`, and the style
    /// words are the only part worth trusting.
    pub fn detect(base_font: &str, flags: i64) -> FallbackStyle {
        let name = base_font.to_ascii_lowercase();
        let bold = name.contains("bold")
            || name.contains("black")
            || name.contains("heavy")
            || name.contains("semibold")
            // Bit 19 (1 << 18) is ForceBold.
            || flags & (1 << 18) != 0;
        let italic = name.contains("italic")
            || name.contains("oblique")
            // Bit 7 (1 << 6) is Italic.
            || flags & (1 << 6) != 0;
        let fixed_pitch = name.contains("courier")
            || name.contains("mono")
            // Bit 1 is FixedPitch.
            || flags & 1 != 0;
        // Bit 2 is Serif; the name decides when the flags are silent.
        let serif = !fixed_pitch && (flags & 2 != 0 || system::looks_serif(&name));
        FallbackStyle {
            bold,
            italic,
            fixed_pitch,
            serif,
        }
    }
}

/// The CJK region whose glyph forms a document expects.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum CjkRegion {
    Japanese,
    SimplifiedChinese,
    TraditionalChinese,
    Korean,
}

impl CjkRegion {
    /// From a CID font's `Registry-Ordering`, e.g. `Adobe-Japan1`.
    pub fn from_collection(collection: &str) -> Option<CjkRegion> {
        let ordering = collection.rsplit('-').next().unwrap_or(collection);
        Some(match ordering {
            "Japan1" | "Japan2" => CjkRegion::Japanese,
            "GB1" => CjkRegion::SimplifiedChinese,
            "CNS1" => CjkRegion::TraditionalChinese,
            "Korea1" | "KR" => CjkRegion::Korean,
            _ => return None,
        })
    }

    /// From the name of a well-known CJK font the document did not embed.
    pub fn from_font_name(name: &str) -> Option<CjkRegion> {
        let name = name.to_ascii_lowercase();
        let any = |words: &[&str]| words.iter().any(|w| name.contains(w));
        if any(&[
            "mincho",
            "gothic-",
            "msgothic",
            "ms-gothic",
            "ms-pgothic",
            "kozuka",
            "hiragino",
            "meiryo",
            "yugothic",
            "heisei",
            "ryumin",
        ]) {
            Some(CjkRegion::Japanese)
        } else if any(&["mingliu", "pmingliu", "msung", "mhei", "dfkai", "kaiu"]) {
            Some(CjkRegion::TraditionalChinese)
        } else if any(&[
            "simsun", "simhei", "stsong", "stheiti", "stkaiti", "yahei", "fangsong", "kaiti",
            "nsimsun",
        ]) {
            Some(CjkRegion::SimplifiedChinese)
        } else if any(&[
            "batang",
            "gulim",
            "dotum",
            "gungsuh",
            "malgun",
            "hysmyeongjo",
            "hygothic",
        ]) {
            Some(CjkRegion::Korean)
        } else {
            None
        }
    }

    /// Words in the family or PostScript names of this region's faces.
    fn font_words(self) -> &'static [&'static str] {
        match self {
            CjkRegion::Japanese => &[
                " jp",
                "cjkjp",
                "cjk jp",
                "hiragino sans",
                "hiragino kaku",
                "hiragino mincho",
                "kaku",
                "mincho",
                "yu gothic",
                "meiryo",
                "ms gothic",
                "osaka",
            ],
            CjkRegion::SimplifiedChinese => &[
                " sc",
                "cjksc",
                "cjk sc",
                "hiragino sans gb",
                "pingfang sc",
                "heiti sc",
                "songti sc",
                "stheiti",
                "yahei",
                "simsun",
                "simhei",
                "gb",
            ],
            CjkRegion::TraditionalChinese => &[
                " tc",
                " hk",
                "cjktc",
                "cjk tc",
                "cjkhk",
                "pingfang tc",
                "pingfang hk",
                "heiti tc",
                "songti tc",
                "mingliu",
                "jhenghei",
            ],
            CjkRegion::Korean => &[
                " kr",
                "cjkkr",
                "cjk kr",
                "sd gothic",
                "apple gothic",
                "applemyungjo",
                "malgun",
                "batang",
                "gulim",
                "nanum",
            ],
        }
    }
}

/// A substitute for one non-embedded font.
pub struct FallbackFont {
    style: FallbackStyle,
    region: Option<CjkRegion>,
}

impl FallbackFont {
    pub fn for_style(style: FallbackStyle) -> Option<FallbackFont> {
        // Roboto always exists; whether a given character can be drawn is
        // decided per character.
        catalog().roboto(style.bold)?;
        Some(FallbackFont {
            style,
            region: None,
        })
    }

    /// Prefer this region's faces for Han characters.
    pub fn with_region(mut self, region: Option<CjkRegion>) -> FallbackFont {
        self.region = region;
        self
    }

    pub fn units_per_em(&self) -> f64 {
        UNITS
    }

    /// Outline for a Unicode character, sheared when a slanted face was asked
    /// for and the face that drew it is upright. `None` when no face has it.
    pub fn outline_for_char(&self, ch: char) -> Option<Path> {
        let (face, gid) = catalog().resolve(ch, self.style, self.region)?;
        let outline = face.font.glyph_outline(gid)?;
        let scale = UNITS / face.font.units_per_em;
        let mut matrix = Matrix::scale(scale, scale);
        if self.style.italic && !face.italic {
            matrix = matrix.then(&Matrix::new(1.0, 0.0, OBLIQUE_SHEAR, 1.0, 0.0, 0.0));
        }
        Some(outline.transform(&matrix))
    }

    /// Advance for a character, in text-space units (em/1000), for use only
    /// when the PDF gave no width of its own.
    pub fn advance(&self, ch: char) -> Option<f64> {
        if self.style.fixed_pitch {
            return Some(600.0);
        }
        let (face, gid) = catalog().resolve(ch, self.style, self.region)?;
        let upem = face.font.units_per_em;
        if upem <= 0.0 {
            return None;
        }
        Some(face.font.advance(gid)? * UNITS / upem)
    }
}

// ---------------------------------------------------------------------------
// The catalog
// ---------------------------------------------------------------------------

/// A face, loaded.
struct Face {
    font: TrueTypeFont,
    italic: bool,
}

/// Where a candidate face comes from.
enum Source {
    Roboto { bold: bool },
    Bundled { index: usize },
    System(FaceInfo),
}

/// A face that might draw a character: what it covers and looks like, and
/// the face itself once something asked for it.
struct Candidate {
    source: Source,
    serif: bool,
    bold: bool,
    italic: bool,
    monospace: bool,
    /// Family and PostScript names, lowercased, for region matching.
    names: String,
    coverage: Vec<(u32, u32)>,
    loaded: OnceLock<Option<Arc<Face>>>,
}

impl Candidate {
    fn covers(&self, ch: u32) -> bool {
        let index = self.coverage.partition_point(|&(lo, _)| lo <= ch);
        index > 0 && ch <= self.coverage[index - 1].1
    }

    fn face(&self) -> Option<Arc<Face>> {
        self.loaded
            .get_or_init(|| {
                let font = match &self.source {
                    Source::Roboto { bold } => TrueTypeFont::parse(
                        if *bold { ROBOTO_BOLD } else { ROBOTO_REGULAR }.to_vec(),
                    ),
                    Source::Bundled { index } => bundled_font(*index),
                    Source::System(info) => system::load_face(&info.path, info.index),
                }?;
                font.has_outlines().then(|| {
                    Arc::new(Face {
                        font,
                        italic: self.italic,
                    })
                })
            })
            .clone()
    }

    /// The glyph for `ch`, when the face really has an outline for it — a
    /// cmap entry pointing at an empty or bitmap-only glyph does not count.
    fn glyph(&self, ch: char) -> Option<(Arc<Face>, u16)> {
        let face = self.face()?;
        let gid = face.font.glyph_for_char(ch as u32)?;
        if gid == 0 {
            return None;
        }
        if !ch.is_whitespace() && face.font.glyph_outline(gid).is_none() {
            return None;
        }
        Some((face, gid))
    }
}

/// Which candidate drew a character, remembered per style and region.
#[derive(Clone, Copy)]
enum Pick {
    Roboto(bool),
    Bundled(usize),
    Latin(usize),
    System(usize),
}

struct Catalog {
    roboto: [Candidate; 2],
    bundled: Vec<Candidate>,
    /// Serif and monospace Latin faces at well-known paths, checked without
    /// a full scan: the standard Times and Courier are too common to make
    /// their first page wait on indexing every installed font.
    latin: OnceLock<Vec<Candidate>>,
    system: OnceLock<Vec<Candidate>>,
    memo: Mutex<HashMap<MemoKey, Option<(Pick, u16)>>>,
}

/// A character in a style and region, for remembering which face drew it.
type MemoKey = (char, FallbackStyle, Option<CjkRegion>);

/// Where the common serif and monospace faces live on each platform.
const LATIN_FACES: &[&str] = &[
    // Android
    "/system/fonts/NotoSerif-Regular.ttf",
    "/system/fonts/NotoSerif-Bold.ttf",
    "/system/fonts/NotoSerif-Italic.ttf",
    "/system/fonts/NotoSerif-BoldItalic.ttf",
    "/system/fonts/DroidSerif-Regular.ttf",
    "/system/fonts/DroidSerif-Bold.ttf",
    "/system/fonts/DroidSerif-Italic.ttf",
    "/system/fonts/DroidSerif-BoldItalic.ttf",
    "/system/fonts/NotoSansMono-Regular.ttf",
    "/system/fonts/DroidSansMono.ttf",
    "/system/fonts/CutiveMono.ttf",
    // iOS and macOS
    "/System/Library/Fonts/Times.ttc",
    "/System/Library/Fonts/Courier.ttc",
    "/System/Library/Fonts/Supplemental/Times New Roman.ttf",
    "/System/Library/Fonts/Supplemental/Times New Roman Bold.ttf",
    "/System/Library/Fonts/Supplemental/Times New Roman Italic.ttf",
    "/System/Library/Fonts/Supplemental/Times New Roman Bold Italic.ttf",
    "/System/Library/Fonts/Supplemental/Courier New.ttf",
    "/System/Library/Fonts/Supplemental/Courier New Bold.ttf",
    "/System/Library/Fonts/Supplemental/Courier New Italic.ttf",
    "/System/Library/Fonts/Supplemental/Courier New Bold Italic.ttf",
    "/System/Library/Fonts/Core/TimesNewRoman.ttf",
    "/System/Library/Fonts/Core/CourierNew.ttf",
    // Windows
    "C:\\Windows\\Fonts\\times.ttf",
    "C:\\Windows\\Fonts\\timesbd.ttf",
    "C:\\Windows\\Fonts\\timesi.ttf",
    "C:\\Windows\\Fonts\\timesbi.ttf",
    "C:\\Windows\\Fonts\\cour.ttf",
    "C:\\Windows\\Fonts\\courbd.ttf",
    "C:\\Windows\\Fonts\\couri.ttf",
    "C:\\Windows\\Fonts\\courbi.ttf",
    // Linux
    "/usr/share/fonts/truetype/liberation/LiberationSerif-Regular.ttf",
    "/usr/share/fonts/truetype/liberation/LiberationSerif-Bold.ttf",
    "/usr/share/fonts/truetype/liberation/LiberationSerif-Italic.ttf",
    "/usr/share/fonts/truetype/liberation/LiberationSerif-BoldItalic.ttf",
    "/usr/share/fonts/truetype/liberation/LiberationMono-Regular.ttf",
    "/usr/share/fonts/truetype/liberation/LiberationMono-Bold.ttf",
    "/usr/share/fonts/truetype/dejavu/DejaVuSerif.ttf",
    "/usr/share/fonts/truetype/dejavu/DejaVuSerif-Bold.ttf",
    "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf",
    "/usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf",
];

fn catalog() -> &'static Catalog {
    static CATALOG: OnceLock<Catalog> = OnceLock::new();
    CATALOG.get_or_init(|| {
        let roboto = |bold: bool| {
            let data = if bold { ROBOTO_BOLD } else { ROBOTO_REGULAR };
            Candidate {
                source: Source::Roboto { bold },
                serif: false,
                bold,
                italic: false,
                monospace: false,
                names: "roboto".into(),
                coverage: sfnt_coverage(data),
                loaded: OnceLock::new(),
            }
        };
        let bundled = bundle_index()
            .iter()
            .enumerate()
            .map(|(index, entry)| Candidate {
                source: Source::Bundled { index },
                serif: entry.serif,
                bold: false,
                italic: false,
                monospace: false,
                names: entry.name.to_ascii_lowercase(),
                coverage: entry.coverage.clone(),
                loaded: OnceLock::new(),
            })
            .collect();
        Catalog {
            roboto: [roboto(false), roboto(true)],
            bundled,
            latin: OnceLock::new(),
            system: OnceLock::new(),
            memo: Mutex::new(HashMap::new()),
        }
    })
}

fn system_candidate(info: FaceInfo) -> Candidate {
    Candidate {
        serif: info.serif,
        bold: info.weight >= 600,
        italic: info.italic,
        monospace: info.monospace,
        names: format!(" {} {}", info.family, info.postscript).to_ascii_lowercase(),
        coverage: info.coverage.clone(),
        source: Source::System(info),
        loaded: OnceLock::new(),
    }
}

impl Catalog {
    fn roboto(&self, bold: bool) -> Option<Arc<Face>> {
        self.roboto[usize::from(bold)].face()
    }

    fn latin(&self) -> &[Candidate] {
        self.latin.get_or_init(|| {
            if !SYSTEM_FONTS.load(Ordering::Relaxed) {
                return Vec::new();
            }
            LATIN_FACES
                .iter()
                .map(std::path::Path::new)
                .filter(|path| path.is_file())
                .flat_map(system::scan_file)
                .filter(usable_system_face)
                .map(system_candidate)
                .collect()
        })
    }

    fn system(&self) -> &[Candidate] {
        self.system.get_or_init(|| {
            if !SYSTEM_FONTS.load(Ordering::Relaxed) {
                return Vec::new();
            }
            let mut dirs = system::default_directories();
            if let Ok(extra) = EXTRA_DIRECTORIES.lock() {
                dirs.extend(extra.iter().cloned());
            }
            system::scan(&dirs)
                .into_iter()
                .filter(usable_system_face)
                .map(system_candidate)
                .collect()
        })
    }

    fn candidate(&self, pick: Pick) -> Option<&Candidate> {
        match pick {
            Pick::Roboto(bold) => Some(&self.roboto[usize::from(bold)]),
            Pick::Bundled(index) => self.bundled.get(index),
            Pick::Latin(index) => self.latin().get(index),
            Pick::System(index) => self.system().get(index),
        }
    }

    /// The best-matching serif or monospace Latin face at a known path.
    fn styled_latin(&self, ch: char, style: FallbackStyle) -> Option<(Pick, Arc<Face>, u16)> {
        let code = ch as u32;
        let mut ranked: Vec<(i64, usize)> = self
            .latin()
            .iter()
            .enumerate()
            .filter(|(_, c)| c.covers(code))
            .filter(|(_, c)| {
                (style.fixed_pitch && c.monospace) || (style.serif && c.serif && !c.monospace)
            })
            .map(|(index, c)| (score(c, style, None), index))
            .collect();
        ranked.sort_by(|a, b| b.0.cmp(&a.0).then(a.1.cmp(&b.1)));
        ranked.into_iter().find_map(|(_, index)| {
            let (face, gid) = self.latin()[index].glyph(ch)?;
            Some((Pick::Latin(index), face, gid))
        })
    }

    fn resolve(
        &self,
        ch: char,
        style: FallbackStyle,
        region: Option<CjkRegion>,
    ) -> Option<(Arc<Face>, u16)> {
        let key = (ch, style, region);
        if let Some(found) = self
            .memo
            .lock()
            .ok()
            .and_then(|memo| memo.get(&key).copied())
        {
            return found.and_then(|(pick, gid)| Some((self.candidate(pick)?.face()?, gid)));
        }
        let found = self.search(ch, style, region);
        if let Ok(mut memo) = self.memo.lock() {
            memo.insert(key, found.as_ref().map(|(pick, _, gid)| (*pick, *gid)));
        }
        found.map(|(_, face, gid)| (face, gid))
    }

    fn search(
        &self,
        ch: char,
        style: FallbackStyle,
        region: Option<CjkRegion>,
    ) -> Option<(Pick, Arc<Face>, u16)> {
        let code = ch as u32;
        let roboto = &self.roboto[usize::from(style.bold)];

        // 1. Latin in the original's style: a serif or monospace design needs
        //    an installed face to look anything like it; sans is Roboto.
        if roboto.covers(code) && (style.serif || style.fixed_pitch) {
            if let Some(found) = self.styled_latin(ch, style) {
                return Some(found);
            }
        }
        if roboto.covers(code) {
            if let Some((face, gid)) = roboto.glyph(ch) {
                return Some((Pick::Roboto(style.bold), face, gid));
            }
        }
        // 2. Bundled scripts, symbols and mathematics.
        for (index, candidate) in self.bundled.iter().enumerate() {
            if candidate.covers(code) {
                if let Some((face, gid)) = candidate.glyph(ch) {
                    return Some((Pick::Bundled(index), face, gid));
                }
            }
        }
        // 3. Installed fonts.
        self.best_system(ch, style, region)
    }

    /// The best installed face for `ch`: the document's CJK region first for
    /// Han, kana and hangul, then the closest design.
    fn best_system(
        &self,
        ch: char,
        style: FallbackStyle,
        region: Option<CjkRegion>,
    ) -> Option<(Pick, Arc<Face>, u16)> {
        let code = ch as u32;
        let han_region =
            cjk_need(ch).map(|need| need.unwrap_or(region.unwrap_or(CjkRegion::SimplifiedChinese)));
        let mut ranked: Vec<(i64, usize)> = self
            .system()
            .iter()
            .enumerate()
            .filter(|(_, c)| c.covers(code))
            .map(|(index, c)| (score(c, style, han_region), index))
            .collect();
        ranked.sort_by(|a, b| b.0.cmp(&a.0).then(a.1.cmp(&b.1)));
        for (_, index) in ranked.into_iter().take(8) {
            if let Some((face, gid)) = self.system()[index].glyph(ch) {
                return Some((Pick::System(index), face, gid));
            }
        }
        None
    }
}

/// For a character that is Han, kana or hangul, the region it belongs to
/// (`Some(None)` for Han, which every region shares).
fn cjk_need(ch: char) -> Option<Option<CjkRegion>> {
    match ch as u32 {
        0x3040..=0x30FF | 0x31F0..=0x31FF | 0xFF66..=0xFF9F => Some(Some(CjkRegion::Japanese)),
        0x1100..=0x11FF | 0x3130..=0x318F | 0xA960..=0xA97F | 0xAC00..=0xD7AF | 0xD7B0..=0xD7FF => {
            Some(Some(CjkRegion::Korean))
        }
        0x2E80..=0x2FDF
        | 0x3000..=0x303F
        | 0x3400..=0x4DBF
        | 0x4E00..=0x9FFF
        | 0xF900..=0xFAFF
        | 0xFF00..=0xFF65
        | 0x20000..=0x3FFFF => Some(None),
        _ => None,
    }
}

/// How well an installed face suits a character in a given style.
fn score(c: &Candidate, style: FallbackStyle, region: Option<CjkRegion>) -> i64 {
    let mut score = 0;
    if let Some(region) = region {
        if region.font_words().iter().any(|w| c.names.contains(w)) {
            score += 100;
        }
    }
    if c.serif == style.serif {
        score += 20;
    }
    if c.monospace == style.fixed_pitch {
        score += 10;
    }
    if c.bold == style.bold {
        score += 8;
    }
    if c.italic == style.italic {
        score += 4;
    }
    // User-interface variants have odd metrics for running text.
    if c.names.contains("interface") || c.names.contains(" ui") {
        score -= 30;
    }
    score
}

/// Installed faces that must never stand in: Apple's hidden system faces
/// (names starting with a dot), the LastResort placeholder font that "covers"
/// every character with a box naming its block, and emoji faces.
fn usable_system_face(info: &FaceInfo) -> bool {
    let family = info.family.trim();
    let lower = format!("{} {}", info.family, info.postscript).to_ascii_lowercase();
    !family.is_empty()
        && !family.starts_with('.')
        && !info.postscript.starts_with('.')
        && !lower.contains("lastresort")
        && !lower.contains("emoji")
}

/// A single-face font's coverage, read through its own cmap.
fn sfnt_coverage(data: &[u8]) -> Vec<(u32, u32)> {
    TrueTypeFont::parse(data.to_vec())
        .map(|font| font.coverage())
        .unwrap_or_default()
}

// ---------------------------------------------------------------------------
// The bundle
// ---------------------------------------------------------------------------

/// One face as the generator hands it over.
pub struct BundledFace {
    pub name: String,
    pub serif: bool,
    pub coverage: Vec<(u32, u32)>,
    pub data: Vec<u8>,
}

struct BundleEntry {
    name: String,
    serif: bool,
    coverage: Vec<(u32, u32)>,
    offset: usize,
    length: usize,
}

/// Serialise faces into the format [`catalog`] reads: an index of names,
/// flags and coverage, then each face deflated on its own so that opening
/// Telugu never inflates Tibetan.
pub fn encode_bundle(faces: &[BundledFace]) -> Vec<u8> {
    let bodies: Vec<Vec<u8>> = faces
        .iter()
        .map(|face| pdf_core::filter::flate_encode(&face.data))
        .collect();
    let mut out = MAGIC.to_vec();
    put_varint(&mut out, faces.len() as u64);
    for (face, body) in faces.iter().zip(&bodies) {
        put_varint(&mut out, face.name.len() as u64);
        out.extend_from_slice(face.name.as_bytes());
        out.push(u8::from(face.serif));
        put_varint(&mut out, face.coverage.len() as u64);
        let mut next = 0u32;
        for &(lo, hi) in &face.coverage {
            put_varint(&mut out, u64::from(lo - next));
            put_varint(&mut out, u64::from(hi - lo));
            next = hi + 1;
        }
        put_varint(&mut out, body.len() as u64);
    }
    for body in bodies {
        out.extend_from_slice(&body);
    }
    out
}

fn bundle_index() -> &'static [BundleEntry] {
    static INDEX: OnceLock<Vec<BundleEntry>> = OnceLock::new();
    INDEX.get_or_init(|| {
        let Some(rest) = BUNDLE.strip_prefix(MAGIC.as_slice()) else {
            return Vec::new();
        };
        let mut at = 0usize;
        let varint = |at: &mut usize| -> Option<u64> {
            let mut value = 0u64;
            for shift in (0..64).step_by(7) {
                let byte = *rest.get(*at)?;
                *at += 1;
                value |= u64::from(byte & 0x7F) << shift;
                if byte & 0x80 == 0 {
                    return Some(value);
                }
            }
            None
        };
        let mut parse = || -> Option<Vec<BundleEntry>> {
            let count = varint(&mut at)? as usize;
            let mut entries = Vec::with_capacity(count);
            for _ in 0..count {
                let len = varint(&mut at)? as usize;
                let name = String::from_utf8(rest.get(at..at + len)?.to_vec()).ok()?;
                at += len;
                let serif = *rest.get(at)? == 1;
                at += 1;
                let ranges = varint(&mut at)? as usize;
                let mut coverage = Vec::with_capacity(ranges);
                let mut next = 0u32;
                for _ in 0..ranges {
                    let lo = next + varint(&mut at)? as u32;
                    let hi = lo + varint(&mut at)? as u32;
                    coverage.push((lo, hi));
                    next = hi + 1;
                }
                let length = varint(&mut at)? as usize;
                entries.push(BundleEntry {
                    name,
                    serif,
                    coverage,
                    offset: 0,
                    length,
                });
            }
            let mut offset = MAGIC.len() + at;
            for entry in &mut entries {
                entry.offset = offset;
                offset += entry.length;
            }
            Some(entries)
        };
        parse().unwrap_or_default()
    })
}

fn bundled_font(index: usize) -> Option<TrueTypeFont> {
    let entry = bundle_index().get(index)?;
    let compressed = BUNDLE.get(entry.offset..entry.offset + entry.length)?;
    TrueTypeFont::parse(pdf_core::filter::flate_decode(compressed).ok()?)
}

fn put_varint(out: &mut Vec<u8>, mut value: u64) {
    loop {
        let byte = (value & 0x7F) as u8;
        value >>= 7;
        if value == 0 {
            out.push(byte);
            return;
        }
        out.push(byte | 0x80);
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn style(bold: bool, italic: bool, fixed_pitch: bool) -> FallbackStyle {
        FallbackStyle {
            bold,
            italic,
            fixed_pitch,
            serif: false,
        }
    }

    fn sans() -> FallbackFont {
        set_system_fonts_enabled(false);
        FallbackFont::for_style(style(false, false, false)).expect("fallback available")
    }

    #[test]
    fn embedded_faces_parse() {
        assert!(
            catalog().roboto(false).is_some(),
            "Roboto-Regular should parse"
        );
        assert!(catalog().roboto(true).is_some(), "Roboto-Bold should parse");
        assert!(bundle_index().len() >= 30, "the Noto bundle is present");
    }

    #[test]
    fn draws_latin_letters() {
        let font = sans();
        for ch in ['A', 'g', '7', '%'] {
            let outline = font.outline_for_char(ch).expect("outline should exist");
            assert!(!outline.is_empty(), "{ch} should have a non-empty outline");
        }
        // A space is a real glyph with no contours; that is not a failure.
        assert!(font.advance(' ').unwrap_or(0.0) > 0.0);
    }

    /// Characters Roboto lacks come from the bundled faces, on any device.
    #[test]
    fn draws_every_bundled_script() {
        let font = sans();
        for ch in [
            'క', 'क', 'ক', 'ਕ', 'ક', 'କ', 'க', 'ಕ', 'ക', 'ක', 'ก', 'ກ', 'ក', 'က', 'ཀ', 'ა', 'Ա',
            'ሀ', 'ބ', 'ܐ', 'ᠠ', 'ꀀ', 'Ꭰ', 'ᐁ', 'ⴰ', 'ߊ', 'ᱚ', 'ꯀ', 'ꦄ', '𞤀', 'א', 'ب', 'ɛ', '∮',
            '✓', '♞',
        ] {
            assert!(
                font.outline_for_char(ch).is_some(),
                "{ch} (U+{:04X}) should be drawable from the bundle",
                ch as u32
            );
        }
    }

    #[test]
    fn outlines_are_normalised_to_a_thousand_units() {
        let font = sans();
        // Roboto's em is 2048; a capital A is roughly 0.7 em tall.
        let (_, _, _, top) = font.outline_for_char('A').unwrap().bounds().unwrap();
        assert!((600.0..800.0).contains(&top), "cap height {top}");
        // Noto's em is 1000; its Telugu letters sit in the same range.
        let (_, _, _, top) = font.outline_for_char('క').unwrap().bounds().unwrap();
        assert!((400.0..1000.0).contains(&top), "Telugu height {top}");
    }

    #[test]
    fn style_detection_reads_subset_prefixed_names() {
        let s = FallbackStyle::detect("ABCDEF+Helvetica-BoldOblique", 0);
        assert!(s.bold && s.italic && !s.fixed_pitch && !s.serif);

        let s = FallbackStyle::detect("Times-Roman", 0);
        assert!(!s.bold && !s.italic && !s.fixed_pitch && s.serif);

        let s = FallbackStyle::detect("Courier", 0);
        assert!(s.fixed_pitch && !s.serif);

        // Descriptor flags stand in when the name says nothing.
        let s = FallbackStyle::detect("SomeFont", (1 << 18) | (1 << 6) | 2);
        assert!(s.bold && s.italic && s.serif);
    }

    #[test]
    fn courier_advances_are_monospaced() {
        set_system_fonts_enabled(false);
        let font = FallbackFont::for_style(style(false, false, true)).unwrap();
        assert_eq!(font.advance('i'), Some(600.0));
        assert_eq!(font.advance('W'), Some(600.0));
    }

    #[test]
    fn proportional_advances_differ_by_glyph() {
        let font = sans();
        let narrow = font.advance('i').unwrap();
        let wide = font.advance('W').unwrap();
        assert!(
            wide > narrow,
            "W ({wide}) should be wider than i ({narrow})"
        );
    }

    #[test]
    fn italic_shear_moves_upper_outline_right() {
        set_system_fonts_enabled(false);
        let upright = sans().outline_for_char('l').unwrap();
        let slanted = FallbackFont::for_style(style(false, true, false))
            .unwrap()
            .outline_for_char('l')
            .unwrap();
        let max_x = |p: &Path| p.bounds().expect("glyph has bounds").2;
        assert!(max_x(&slanted) > max_x(&upright));
    }

    #[test]
    fn regions_come_from_collections_and_font_names() {
        assert_eq!(
            CjkRegion::from_collection("Adobe-Japan1"),
            Some(CjkRegion::Japanese)
        );
        assert_eq!(
            CjkRegion::from_collection("Adobe-GB1"),
            Some(CjkRegion::SimplifiedChinese)
        );
        assert_eq!(CjkRegion::from_collection("Adobe-Identity"), None);
        assert_eq!(
            CjkRegion::from_font_name("MS-Mincho"),
            Some(CjkRegion::Japanese)
        );
        assert_eq!(
            CjkRegion::from_font_name("SimSun"),
            Some(CjkRegion::SimplifiedChinese)
        );
        assert_eq!(
            CjkRegion::from_font_name("MingLiU"),
            Some(CjkRegion::TraditionalChinese)
        );
        assert_eq!(CjkRegion::from_font_name("Batang"), Some(CjkRegion::Korean));
        assert_eq!(CjkRegion::from_font_name("Helvetica"), None);
    }

    #[test]
    fn placeholder_and_hidden_faces_never_stand_in() {
        let info = |family: &str, postscript: &str| FaceInfo {
            path: PathBuf::new(),
            index: 0,
            family: family.into(),
            postscript: postscript.into(),
            weight: 400,
            italic: false,
            serif: false,
            monospace: false,
            coverage: vec![(0, 0x10FFFF)],
        };
        assert!(!usable_system_face(&info(".LastResort", "LastResort")));
        assert!(!usable_system_face(&info(
            ".Apple SD Gothic NeoI",
            ".AppleSDGothicNeoI-Regular"
        )));
        assert!(!usable_system_face(&info(
            "Apple Color Emoji",
            "AppleColorEmoji"
        )));
        assert!(usable_system_face(&info(
            "Hiragino Sans",
            "HiraginoSans-W3"
        )));
    }

    #[test]
    fn han_prefers_the_documents_region() {
        let candidate = |names: &str| Candidate {
            source: Source::Roboto { bold: false },
            serif: false,
            bold: false,
            italic: false,
            monospace: false,
            names: names.into(),
            coverage: Vec::new(),
            loaded: OnceLock::new(),
        };
        let japanese = candidate(" hiragino sans hiraginosans-w3");
        let korean = candidate(" apple sd gothic neo applesdgothicneo-regular");
        let s = style(false, false, false);
        assert!(
            score(&japanese, s, Some(CjkRegion::Japanese))
                > score(&korean, s, Some(CjkRegion::Japanese))
        );
        assert!(
            score(&korean, s, Some(CjkRegion::Korean))
                > score(&japanese, s, Some(CjkRegion::Korean))
        );
        assert_eq!(cjk_need('中'), Some(None));
        assert_eq!(cjk_need('あ'), Some(Some(CjkRegion::Japanese)));
        assert_eq!(cjk_need('한'), Some(Some(CjkRegion::Korean)));
        assert_eq!(cjk_need('A'), None);
    }
}
